### ISSUE TITLE
Using prometheus or netdata with skyline

### ISSUE THREAD

**Issue by 3c2b2ff5** [earthgecko/skyline#161]
Hi,

I am wondering if it is possible to use skyline with prometheus or netdata?

Thanks

**Comment by earthgecko** [comment]
Hi @3c2b2ff5 you can, but you still need to populate Graphite with the metrics.  Both Prometheus and netdata can send data to a Graphite backend, both have documentation of how to configure this.

It is also possible for Skyline to fetch a selection of metrics from Prometheus using Vista and Flux to populate Graphite and Skyline - see https://earthgecko-skyline.readthedocs.io/en/latest/vista.html

If you are interested Anomalarm is starting to offer a managed service with a custom UI and are looking for test partners during the beta phase, if you are interested contact details are in the readme.md of the front page of this repo.

**Comment by 3c2b2ff5** [comment]
@earthgecko thanks a lot for the quick reply. I am going now through the documentation, just to have a basic understanding.
We are definitely interested and will contact you.
Thanks a lot for the offer.
