### ISSUE TITLE
AttributeError: 'list' object has no attribute 'metric' - Panorama not working 

### ISSUE THREAD

**Issue by odonthu** [earthgecko/skyline#255]
Hello Team,

I am getting the following error in fresh installation:

2020-07-11 03:17:06 :: 29074 :: Traceback (most recent call last):
  File "/opt/skyline/github/skyline/skyline/panorama/panorama.py", line 740, in spin_process
    metric_vars_array = self.new_load_metric_vars(str(metric_check_file))
  File "/opt/skyline/github/skyline/skyline/panorama/panorama.py", line 478, in new_load_metric_vars
    'debug :: metric_vars determined - metric variable - metric - %s' % str(metric_vars.metric))
AttributeError: 'list' object has no attribute 'metric'

I can not any entries in skyline database. No entries in anomaly's table and metrics table. Panorama not working

**Comment by earthgecko** [comment]
Hi @odonthu

Thanks for reporting that.  This is a bug, it is related to some `ENABLE_DEBUG` logging left over from the old 
Python 2.6 imp method.  It was missed in the method change in the py3 branch as it has not run with
`ENABLE_DEBUG`.  I have corrected it.

You can replace your `/opt/skyline/github/skyline/skyline/panorama/panorama.py` with https://raw.githubusercontent.com/earthgecko/skyline/b0be5e498f441271dc0a61ec79a254cc08196303/skyline/panorama/panorama.py

```
cp /opt/skyline/github/skyline/skyline/panorama/panorama.py /opt/skyline/github/skyline/skyline/panorama/panorama.py.bak
wget -O /opt/skyline/github/skyline/skyline/panorama/panorama.py https://raw.githubusercontent.com/earthgecko/skyline/b0be5e498f441271dc0a61ec79a254cc08196303/skyline/panorama/panorama.py
```

Restart Panorama and run seed_data.py again and that should resolve the issue.

**Comment by odonthu** [comment]
Hello Team,

Thank you for the response.

I have made ENABLED_DEBUG=False
still panorama is not getting any metrics
I can see in analyzer.log ( sent_to_panorama :: 0 )
could you please help me what could be the issue
why analyser is not able to send any metrics/anomalies to panorama

**Comment by earthgecko** [comment]
Closing as resolved odonthu's other configuration issue in gitter.
