### ISSUE TITLE
[Q] How do I make a metrics appear and select it in the "metric name" section?

### ISSUE THREAD

**Issue by angry-tony** [earthgecko/skyline#418]
I have successfully installed skyline and graphite on the same VM using the script provided on github.
As there is no special error log on the skyline log, everything seems to be normal.
- Graphite & skyline is available at http://skyline-test.kekehoho.com:8888 & https://skyline-test.kekehoho.com.
I left the skyline for about a day, but nothing is displayed in the "metric name" section.
I am wondering what additional settings are needed to show it.
How do I make a metrics appear and select it in the "metric name" section?

Is there anyone who can help me?
![캡처](https://user-images.githubusercontent.com/18000837/112705417-fbe7f280-8ee1-11eb-8214-a904b8169ccc.PNG)

**Comment by earthgecko** [comment]
Hi @angry-tony you need to send metrics to Skyline and there needs to have been some anomalies for there to be info in the pages.

You can check that metrics are being submitted to Skyline by doing the following:

- Click the rebrow menu
- Click connect
- In the All keys search box type `metrics.unique_metrics`

![image](https://user-images.githubusercontent.com/96679/112714126-c555ac00-8ed0-11eb-80b4-d0fe45914b23.png)

- Click on `metrics.unique_metrics` key and it will show you what metric have been submitted.

You can use rebrow to look at any metrics that have been submitted to see the they have current data by entering `metrics.*` in the rebrow All keys search box.

If you are not sending metrics to the Skyline instance, Skyline will not be doing anything.
If you have no metrics, you can just install telegraf on the VM and configure it to send to the Graphite instance on the VM.  If you used the skyline.dawn.sh script then after installing telegraf on the VM configure the `[[outputs.graphite]]` in /etc/telegraf/telegraf.conf as follows:

```
[[outputs.graphite]]
#   ## TCP endpoint for your graphite instance.
#   ## If multiple endpoints are configured, output will be load balanced.
#   ## Only one of the endpoints will be written to with each iteration.
  servers = ["127.0.0.1:2003"]
```

And restart telegraf

```
systemctl restart telegraf
```

You can then browse Graphite on the VM and see the telegraf metrics are there.

To have Skyline analyse those, you will have configure the `ALERTS` and `SMTP_OPTIONS` section in skyline/settings.py as follows:

```
ALERTS = (
    ('skyline', 'smtp', 3600),
    ('carbon', 'smtp', 3600),
    ('telegraf', 'smtp', 3600),
)
```
And
```
SMTP_OPTS = {
    # This specifies the sender of email alerts.
    'sender': 'no_email',
    # recipients is a dictionary mapping metric names
    # (exactly matching those listed in ALERTS) to an array of e-mail addresses
    'recipients': {
        'telegraf': ['no_email'],
        'skyline': ['no_email'],
        'carbon': ['no_email'],
    },
    # This is the default recipient which acts as a catchall for alert tuples
    # that do not have a matching namespace defined in recipients
    'default_recipient': ['no_email'],
    'embed-images': True,
}
```

And then restart analyzer.

```
sudo -u skyline /opt/skyline/github/skyline/bin/analyzer.d stop
sudo -u skyline /opt/skyline/github/skyline/bin/analyzer.d start
```

Leave it running and after a day you should see stuff in the Panorama and Ionosphere pages.

After you have got metrics being submitted to Skyline you can look at the /var/log/skyline/analyzer.log and you should see info about the number of metrics analysed, etc

```
2021-03-27 08:12:59 :: 200461 :: seconds to run     :: 21.25
2021-03-27 08:12:59 :: 200461 :: total metrics      :: 1528
2021-03-27 08:12:59 :: 200461 :: total analyzed     :: 657
2021-03-27 08:12:59 :: 200461 :: total anomalies    :: 0
2021-03-27 08:12:59 :: 200461 :: exception stats    :: {'Boring': 747, 'Stale': 108, 'TooShort': 16, 'Other': 0, 'EmptyTimeseries': 0}
2021-03-27 08:12:59 :: 200461 :: anomaly breakdown  :: {'histogram_bins': 0, 'first_hour_average': 0, 'stddev_from_average': 0, 'grubbs': 0, 'ks_test': 0, 'mean_subtraction_cumulation': 0, 'median_absolute_deviation': 0, 'stddev_from_moving_average': 0, 'least_squares': 0, 'abs_stddev_from_median': 0, 'last_same_hours': 0}
```

I hope this helps.

**Comment by angry-tony** [comment]
Thank you so much for reply.
I'll do what you told me to do.

**Comment by angry-tony** [comment]
@earthgecko 
it's appear metrics.
thank you for your kind.
