### ISSUE TITLE
Keep up the good work

### ISSUE THREAD

**Issue by blak3r2** [earthgecko/skyline#44]
Hey Gary, 

We worked together a bit last year.  I'm no longer have access to my old email.  Great to see you're still working on this.  blake.robertson@gmail.com

**Comment by earthgecko** [comment]
@blak3r hey there Blake, good to hear from you.  Yes still working on it.  One has to sometimes ask one's self, have you strayed too for into ```no man's land```? :)

I will hit you up on the email above and you may want to edit that comment above and ```redacted``` your address there, I checked you do not have it on your profile page, so if you do not want the _MILLIONS_ of spam bots that devour earthgecko/skyline, like ravenous herds, to parse that, I suggest you edit and ```redacted``` it.  LOL

_MILLIONS_ is the name of a mythical organisation that does not exist, but if they did they would be rumoured to have spam bots and would have an **avid** interest in earthgecko/skyline, however they are mythical.

However, that said, there are spam bots out there and ....  mining bots,  However I doubt ANY of them have an interest in earthgecko/skyline, however if there was an organisation or group of entities that were interested in mining github were/are out there, (_which for these purposes here, we shall hereafter refer to these aforemention entities as the ANY party_), they could have/would definitely have bots for aforementioned purposes and therefore by association of earthgecko/skyline with the party known as github.com, then at some point a bot **might** parse this.  Although, in all probability, at no point soon, a spam bot that is.

Now API bots ... that is an entirely different, whole other can of cans, I am certain.  Who knows what they get up to?  Gamification of the masses.

Keeping up the good work.  I am not 100% certain it is good work, but it works, (I think) :)
