### ISSUE TITLE
ValueError: can't have unbuffered text I/O

### ISSUE THREAD

**Issue by wtyj112** [earthgecko/skyline#484]
using docker compose 
when  run skyline got error ValueError: can't have unbuffered text I/O
i try modify file utils/python-daemon/runner.3.0.0.py  row 135,  It doesn't work

skyline-skyline-docker-skyline-1-1  | error - failed to start panorama
skyline-skyline-docker-skyline-1-1  | Traceback (most recent call last):
skyline-skyline-docker-skyline-1-1  |   File "/skyline/skyline/horizon/agent.py", line 203, in <module>
skyline-skyline-docker-skyline-1-1  |     run()
skyline-skyline-docker-skyline-1-1  |   File "/skyline/skyline/horizon/agent.py", line 197, in run
skyline-skyline-docker-skyline-1-1  |     daemon_runner = runner.DaemonRunner(horizon)
skyline-skyline-docker-skyline-1-1  |   File "/usr/local/lib/python3.8/site-packages/daemon/runner.py", line 114, in __init__
skyline-skyline-docker-skyline-1-1  |     self._open_streams_from_app_stream_paths(app)
skyline-skyline-docker-skyline-1-1  |   File "/usr/local/lib/python3.8/site-packages/daemon/runner.py", line 134, in _open_streams_from_app_stream_paths
skyline-skyline-docker-skyline-1-1  |     self.daemon_context.stderr = open(
skyline-skyline-docker-skyline-1-1  | ValueError: can't have unbuffered text I/O
skyline-skyline-docker-skyline-1-1  | error - failed to start horizon
skyline-skyline-docker-skyline-1-1  | [2022-01-07 08:18:19 +0000] [144] [INFO] Starting gunicorn 20.1.0
skyline-skyline-docker-skyline-1-1  | [2022-01-07 08:18:19 +0000] [144] [INFO] Listening at: http://127.0.0.1:8000 (144)
skyline-skyline-docker-skyline-1-1  | [2022-01-07 08:18:19 +0000] [144] [INFO] Using worker: sync
skyline-skyline-docker-skyline-1-1  | [2022-01-07 08:18:19 +0000] [147] [INFO] Booting worker with pid: 147
skyline-skyline-docker-skyline-1-1  | /usr/local/lib/python3.8/importlib/__init__.py:127: DeprecatedWarning: Call to deprecated function __init__(...). API class may be removed in a future release, use falcon.App instead.
skyline-skyline-docker-skyline-1-1  |   return _bootstrap._gcd_import(name[level:], package, level)
skyline-skyline-docker-skyline-1-1  | flux started with pid 144
skyline-skyline-docker-skyline-1-1  | Traceback (most recent call last):
skyline-skyline-docker-skyline-1-1  |   File "/skyline/skyline/vista/agent.py", line 117, in <module>
skyline-skyline-docker-skyline-1-1  |     run()
skyline-skyline-docker-skyline-1-1  |   File "/skyline/skyline/vista/agent.py", line 108, in run
skyline-skyline-docker-skyline-1-1  |     daemon_runner = runner.DaemonRunner(vista)
skyline-skyline-docker-skyline-1-1  |   File "/usr/local/lib/python3.8/site-packages/daemon/runner.py", line 114, in __init__
skyline-skyline-docker-skyline-1-1  |     self._open_streams_from_app_stream_paths(app)
skyline-skyline-docker-skyline-1-1  |   File "/usr/local/lib/python3.8/site-packages/daemon/runner.py", line 134, in _open_streams_from_app_stream_paths
skyline-skyline-docker-skyline-1-1  |     self.daemon_context.stderr = open(
skyline-skyline-docker-skyline-1-1  | ValueError: can't have unbuffered text I/O
skyline-skyline-docker-skyline-1-1  | error - failed to start vista
skyline-skyline-docker-skyline-1-1  | Traceback (most recent call last):
skyline-skyline-docker-skyline-1-1  |   File "/skyline/skyline/analyzer/agent.py", line 147, in <module>
skyline-skyline-docker-skyline-1-1  |     run()
skyline-skyline-docker-skyline-1-1  |   File "/skyline/skyline/analyzer/agent.py", line 138, in run
skyline-skyline-docker-skyline-1-1  |     daemon_runner = runner.DaemonRunner(analyzer)
skyline-skyline-docker-skyline-1-1  |   File "/usr/local/lib/python3.8/site-packages/daemon/runner.py", line 114, in __init__
skyline-skyline-docker-skyline-1-1  |     self._open_streams_from_app_stream_paths(app)
skyline-skyline-docker-skyline-1-1  |   File "/usr/local/lib/python3.8/site-packages/daemon/runner.py", line 134, in _open_streams_from_app_stream_paths
skyline-skyline-docker-skyline-1-1  |     self.daemon_context.stderr = open(
skyline-skyline-docker-skyline-1-1  | ValueError: can't have unbuffered text I/O
skyline-skyline-docker-skyline-1-1  | error - failed to start analyzer

**Comment by earthgecko** [comment]
Hi @wtyj112 there is a modification required to runner.py however it is not `utils/python-daemon/runner.3.0.0.py` that needs modifying in your case it is `/usr/local/lib/python3.8/site-packages/daemon/runner.py` on the docker instance. `utils/python-daemon/runner.3.0.0.py` is an example of what changes need to be made to the **local** `runner.py`.  That change will need to be implemented **AFTER** starting **every time** and only then can the applications to be started.

This is an example of one the many reasons why support for docker has been **discontinued**.  If you wish to continued trying to get it to work with docker, I would suggest making your own build with your own Dockerfile and images that suit your implementation.  If you want to continue with your own docker build I suggest you download  https://raw.githubusercontent.com/earthgecko/skyline/master/utils/python-daemon/runner.3.0.0.py and diff it against `/usr/local/lib/python3.8/site-packages/daemon/runner.py` and create a docker build that implements that change appropriately.

However, I would strongly recommend *not* running Skyline with Docker.
