### ISSUE TITLE
 feature section

### ISSUE THREAD

**Issue by Shuimo03** [earthgecko/skyline#638]
I found an extra invalid node in a section of FEATURE and I wish I could fix it.

[overview](https://github.com/earthgecko/skyline/blob/master/docs/overview.rst)

Features
--------

- Skyline use the most appropriate state of the art algorithms for real time
  anomaly detection.
- Uses multi stage analysis and filtering to allow for the use of more time complex
  algorithms to be applied in the real time domain.
- Puts the user in control of false positive detections by allowing for
  simple user input to provide explainable ML methods with training data which
  massively reduce false positive detections and provides the system with data
  to begin learning with.
-

**Comment by earthgecko** [comment]
Hi @Shuimo03 thank you this orphaned list item will be removed in the next docs build.
